# -*- coding: utf-8 -*-
"""The app's colour themes (#278): one table, two templates.

Roberto's brief of 6 Sep 2026: a reader picks a theme, and the sun-and-moon
toggle switches light and dark *within* it. Navy is the default and is the
page exactly as it was; the others are the palettes he approved on the
rendered sheets kept in Notes/themes_2026-09-06/ (the original thirteen,
one of which -- Walnut -- was dropped by #307) and Notes/themes_2026-09-07/
(#326: Bayerische, the BMW M stripe, and Macaw, from his own photograph
of a scarlet macaw; each was drawn twice there, with the two accents it
could take, and he chose the red button and the gold one).

Each theme is twenty-two values -- five for the banner, seven for the
results panel, ten per mode for the page -- and everything else the two
stylesheets need (the soft rule, the code background, the note tint, the
placeholder, the focus ring ...) is derived from those here, the same way
for every theme, so a new theme is a row in TABLE and nothing else.

    python tools/palettes.py write    # regenerate the blocks in both templates
    python tools/palettes.py check    # fail if either block is stale

The blocks sit between the markers below. build_local.py runs `check` on
every build, so a hand edit inside the markers is caught rather than kept.

Navy deliberately has no block: it is the templates' own :root and
html[data-theme="dark"], untouched, and `data-palette` is simply absent
from the root element. That is what keeps today's page byte-for-byte the
default. The dark-mode button hover was #1f4a86 in both modes until this
item -- the light theme's dark blue on a #5b96e0 button -- and Navy's dark
block now says #4a86d0; that one line is Navy's whole change.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CR, LF = chr(13), chr(10)
SERVER = HERE.parent
TEMPLATES = ["templates/index.html", "templates/eqsheet.html"]

BEGIN = "/* ==== BEGIN palettes (#278) ==== generated by tools/palettes.py; do not edit */"
END = "/* ==== END palettes (#278) ==== */"

# key, English name (the dictionaries carry the translations under
# js.palette.<key>), then the twenty-two values in the sheet's order:
#   banner: top band, ribbon, numeral + keyline, subtitle, ribbon link
#   panel:  gradient top, ground, border, row line, readout ink, dim, name
#   light:  ground, card, ink, muted, accent, accent ink, rule, field,
#           field border, button hover
#   dark:   the same ten
# The order of TABLE is the menu's order, and `PALETTES` in both
# templates must match it -- that array is hand-kept, not generated here,
# which is how the two drifted (#334).
#
# The order is chromatic: sorted by the hue of each theme's banner band,
# walking forward round the wheel from Navy's blue, with Navy first
# because it is the default. The two near-achromatic themes are taken out
# of the walk and put at the end -- Gray & Gold next to last, Contrast
# last -- since a hue means nothing at that saturation.
#
# A new theme goes at its hue, not at the end and not at the top. All
# three of the newest ones went in near the top, which is what #334 had
# to undo; Ara macao is the one that showed, a scarlet sitting between
# two blues.
TABLE = [
    ("navy", "Default",
     "#203864 #2a4576 #8ec7f5 #b7c3d6 #dbe6f5",
     "#102338 #0d1e30 #081525 #173352 #8ecbff #4a7098 #6fb8f0",
     "#f4f6fa #ffffff #1c2330 #5b6472 #2f5fa8 #ffffff #e2e5ea #fbfcfd #cfd6df #1f4a86",
     "#12161d #1b212c #e4e8ee #97a3b6 #5b96e0 #0d1420 #2b3341 #11161e #38424f #4a86d0"),
    ("violet", "Violet",
     "#363a80 #42478f #b9bdff #bfc1e6 #e0e1f8",
     "#1b1d44 #14163a #0a0b22 #2b2e60 #c6c5ff #6b6ca8 #a3a1ff",
     "#f5f5fc #ffffff #1f1f38 #5f6180 #5652c8 #ffffff #e0e1f0 #fbfbff #cbcde6 #4340a8",
     "#13142a #1c1d38 #e7e7f6 #9c9ec4 #9d9bff #12132a #2d2f52 #0f1024 #3b3d66 #b4b2ff"),
    ("pastels", "Pastels",
     "#7f74ad #8d83b8 #ffe9a8 #ece7f7 #f6f3fc",
     "#47406c #3e3860 #2e2a48 #565080 #c8f5dc #9a93bf #f7c7d9",
     "#f8f6fb #ffffff #3a3550 #7a7494 #e79ab0 #3a3550 #e8e3f2 #fcfbfe #d8d1e8 #f0b0c2",
     "#221f30 #2c2840 #ece8f5 #aaa3c4 #f2b8c8 #221f30 #3f3a56 #1d1a2a #4c4666 #f8cbd8"),
    ("warmpink", "Warm Pink",
     "#5c1a45 #6c2654 #f3a6d3 #d9b3cb #f3dbe9",
     "#2b0f22 #21091a #12050e #43203a #ffb6de #8a5a78 #f08cc4",
     "#fbf5f8 #ffffff #2a1a24 #6f5866 #b02a72 #ffffff #ecdde5 #fdfafc #dcc6d3 #8f1f5b",
     "#1a1015 #24161f #f2e6ed #ad93a3 #ea6fb4 #1a1015 #3a2833 #160d12 #4a3341 #f08cc4"),
    ("burgundy", "Burgundy",
     "#4f1424 #5f1d30 #f0a9b8 #d4aab4 #f3dae0",
     "#2a0c14 #200810 #100408 #44182a #ffb8c6 #8c5868 #f28aa0",
     "#faf4f5 #ffffff #2c1a1f #6f5860 #8c1d38 #ffffff #ebdde0 #fdfafb #dcc6cb #6e1329",
     "#1a1114 #251a1e #f2e6e9 #ad949b #e3708c #1a1114 #3c2a30 #150e11 #4c373e #ee92a8"),
    ("macaw", "Ara macao",
     "#bb1f14 #cb2419 #ffc61e #f6cdc6 #ffe4de",
     "#16309b #0f2585 #060f3d #2447c4 #ffd75e #7f93da #ff7a63",
     "#fbf7f4 #ffffff #241a17 #6f6058 #1b46c8 #ffffff #ece0da #fefcfa #ddcbc2 #123aa8",
     "#16110f #1f1815 #f0e7e1 #b09a92 #6f9dff #16110f #3a2b26 #120d0b #4b3831 #9dbcff"),
    ("brick", "Brick",
     "#6a2c20 #7b392c #f4b79e #d8b3a6 #f5e1da",
     "#2d1611 #23100c #120705 #4a2820 #ffbfa6 #8f5c4c #f39678",
     "#faf4f1 #fffdfc #2e1c17 #715a53 #a53f2b #ffffff #ecdcd6 #fdfaf8 #dcc6bf #86311f",
     "#1b1210 #261915 #f1e4df #b0958c #e27a5e #1b1210 #3d2a25 #160e0c #4e3730 #ee9a82"),
    ("earth", "Earth",
     "#4a3a2a #594736 #dcbb87 #cdbca4 #ecdfcc",
     "#2a2016 #201810 #100b07 #43352a #eacd9e #8a7250 #d7b078",
     "#f8f4ee #fffdf9 #2d2419 #6f6152 #8a5a2b #ffffff #e6dccf #fdfaf5 #d5c8b6 #6e4620",
     "#1a1512 #241d18 #ede4d8 #ab9c8a #d3a262 #1a1512 #3a3028 #15100d #4a3e33 #e2b87d"),
    ("forest", "Forest",
     "#1e3d2b #294a36 #a8d8a0 #b3c9b8 #dcebdf",
     "#14301f #0f2418 #061209 #1f4430 #b8ecb8 #5a8a66 #8fd49a",
     "#f3f7f3 #fffefc #172519 #566b5a #2c6e42 #ffffff #dbe6dc #fbfdfb #c6d8c9 #215532",
     "#0f1712 #16221a #e4eee5 #92ab97 #6cc488 #0f1712 #26362b #0c130e #33473a #8ad8a1"),
    ("firefly", "Firefly",
     "#0a1810 #122419 #e3f56b #8fb09a #d2e8c8",
     "#0e2418 #081a10 #030d07 #1a3a26 #e8ff7a #4e7a56 #b9ec5c",
     "#f1f5ee #fbfdf8 #16261b #52685a #4f7f21 #ffffff #d5e1d3 #f7faf4 #bdd0bf #3d6418",
     "#070f0a #0d1a12 #d9ecd2 #7fa088 #d6f253 #0a1a10 #1c3324 #050b07 #23402c #e8ff7a"),
    ("turquoise", "Aqua",
     "#0f4a58 #175a69 #7fe3d6 #a9d3cf #d6f1ec",
     "#0b2f36 #08252b #041418 #164048 #8ef0e2 #3f8a84 #5fd6c8",
     "#f4f8f5 #fffefb #14302e #56706c #0f8a82 #ffffff #dbe8e3 #fbfdfb #c4d9d3 #0b6d67",
     "#0e1b1c #142628 #e3f0ec #8fb2ac #45d0c2 #0a1a1a #23393a #0b1617 #2f4a4b #6ee0d4"),
    ("ararauna", "Ara ararauna",
     "#0a536f #0d6486 #ffb31a #a9dcef #cfeaf6",
     "#0d3f6b #0a3054 #04182b #145181 #ffc55e #5f8bb0 #7fd0ea",
     "#fbf8f0 #ffffff #1e2528 #5f6b70 #f2a30c #1e2528 #e6e0d2 #fefdf9 #d9d2c0 #d18f00",
     "#101619 #182024 #e9eef0 #93a3ab #ffb31a #101619 #26333a #0d1416 #35454e #ffc857"),
    ("bayerische", "Bayerische",
     "#16588e #1d68a4 #81c4ff #b3d3ee #dceafc",
     "#0b2f4d #08243a #04121f #14456e #a8d8ff #4f7ea6 #ff5a63",
     "#f4f7fb #ffffff #12222f #5a6b7a #cf1f2a #ffffff #dfe6ee #fbfcfe #cbd7e3 #a9151f",
     "#0f1720 #17212c #e2e9f1 #93a4b6 #ff5a63 #0f1720 #263443 #0d151d #35455a #ff7f86"),
    ("graygold", "Gray & Gold",
     "#3b4048 #484e57 #d9aa4c #b8bec6 #e2e6ea",
     "#23282e #1a1e22 #0d0f11 #343a41 #f0c070 #7d7466 #d9aa4c",
     "#f2f3f4 #ffffff #1e2125 #5f666e #b3781e #ffffff #dde0e3 #fafbfb #c8cdd3 #8f5e14",
     "#141618 #1d2023 #e6e8ea #9aa1a8 #e0a83c #141618 #2d3135 #101214 #3d4247 #f0bd5e"),
    ("highcontrast", "Contrast",
     "#000000 #111111 #ffd400 #dddddd #ffffff",
     "#000000 #000000 #ffffff #444444 #ffffff #bbbbbb #ffd400",
     "#ffffff #ffffff #000000 #333333 #0000c8 #ffffff #000000 #ffffff #000000 #000080",
     "#000000 #000000 #ffffff #dddddd #ffd400 #000000 #ffffff #000000 #ffffff #ffe866"),
]

# The accent as TEXT, where it must differ from the accent as a BUTTON.
#
# `--accent` is both: the Solve button's ground and the colour of links,
# section headings, the [ I N P U T S ] brackets and a plot line. For twelve
# themes one value serves both, and this table is empty for them.
#
# Macaw cannot: Roberto chose its gold button (#326), and gold on the warm
# page measures 1.94:1 as text -- handsome as a button, faint as a link. The
# bird settles it. A scarlet macaw is a scarlet BIRD with gold on the wing
# and blue on the flight feathers, and the theme had the gold and the blue
# and none of the red (Roberto, 8 Sep 2026: "add some red highlights ... so
# it's not just dominated by blue and yellow"). So the text accent is the
# bird's own scarlet: 5.25:1 on the light page, 7.08:1 on the dark.
#
# A theme listed here also derives --accent-open from this value rather than
# from the accent, or an OPEN section heading would go gold while a closed
# one stayed scarlet.
ACCENT_TEXT = {
    "macaw": {"light": "#c62a1c", "dark": "#ff7a63"},
    # Ara ararauna's button is the bird's gold, which measures 1.97:1 as text
    # on the warm page -- the same trap Macaw was in. Its links, headings and
    # brackets take the wing blue instead (6.85:1), and on the dark page the
    # baby blue Roberto pointed at in the first photograph (10.53:1).
    "ararauna": {"light": "#0d5c85", "dark": "#7fd0ea"},
}

KEYS = [row[0] for row in TABLE]
NAMES = dict((row[0], row[1]) for row in TABLE)


# --- colour arithmetic ------------------------------------------------------

def _rgb(h: str) -> tuple:
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _hex(rgb) -> str:
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(round(c)))) for c in rgb)


def mix(a: str, b: str, t: float) -> str:
    """a moved t of the way towards b."""
    ra, rb = _rgb(a), _rgb(b)
    return _hex(tuple(x + (y - x) * t for x, y in zip(ra, rb)))


def rgba(h: str, alpha: float) -> str:
    return "rgba(%d,%d,%d,%s)" % (_rgb(h) + (alpha,))


def rgb_list(h: str) -> str:
    return "%d,%d,%d" % _rgb(h)


# --- the theme record --------------------------------------------------------

def theme(row) -> dict:
    key, name, banner, panel, light, dark = row
    b = banner.split()
    p = panel.split()
    modes = {}
    for mode, values in (("light", light), ("dark", dark)):
        v = values.split()
        modes[mode] = dict(zip(
            ("bg", "card", "ink", "muted", "accent", "accent_ink", "line",
             "field", "field_line", "hover"), v))
    return dict(
        key=key, name=name,
        navy=b[0], navy2=b[1], sky=b[2], sub=b[3], link=b[4],
        lcd_top=p[0], lcd_bg=p[1], lcd_border=p[2], lcd_line=p[3],
        lcd_ink=p[4], lcd_dim=p[5], lcd_name=p[6],
        light=modes["light"], dark=modes["dark"],
    )


THEMES = [theme(r) for r in TABLE]


def _decl(pairs) -> str:
    return "".join("    %s: %s;\n" % kv for kv in pairs)


# --- the app page (index.html) ------------------------------------------------

def atext(t: dict, m: dict, mode: str) -> str:
    """The accent as text: the theme's own, or the accent itself."""
    return ACCENT_TEXT.get(t["key"], {}).get(mode, m["accent"])


def app_page_vars(t: dict, m: dict, mode: str) -> list:
    """The page's own tokens for one mode, in the order :root declares them."""
    extra = ([("--accent-text", atext(t, m, mode))]
             if t["key"] in ACCENT_TEXT else [])
    return extra + [
        ("--bg", m["bg"]), ("--card", m["card"]), ("--ink", m["ink"]),
        ("--muted", m["muted"]), ("--accent", m["accent"]),
        ("--accent-ink", m["accent_ink"]),
        ("--accent-open", mix(atext(t, m, mode),
                              m["card"] if mode == "dark" else m["ink"], 0.15)),
        ("--accent-hover", m["hover"]),
        ("--line", m["line"]), ("--line-soft", mix(m["line"], m["bg"], 0.5)),
        ("--placeholder", mix(m["muted"], m["bg"], 0.45)),
        ("--focus-line", m["accent"]),
        ("--focus-ring", "0 0 0 3px " + rgba(m["accent"], 0.18)),
        ("--btn-disabled", mix(m["muted"], m["bg"], 0.5)),
        ("--solve-shadow-rgb", rgb_list(m["hover"])),
        ("--field-bg", m["field"]), ("--field-bg-focus", m["card"]),
        ("--field-border", m["field_line"]),
        ("--field-border-hover", mix(m["field_line"], m["ink"], 0.3)),
        ("--code-bg", mix(m["card"], m["line"], 0.55)),
        ("--note-bg", mix(m["card"], m["accent"], 0.08)),
        ("--note-line", mix(m["card"], m["accent"], 0.4)),
    ]


def app_shared_vars(t: dict) -> list:
    """The banner and the results panel: the same in both modes."""
    return [
        ("--navy", t["navy"]), ("--navy-2", t["navy2"]), ("--sky", t["sky"]),
        ("--banner-sub", t["sub"]), ("--banner-link", t["link"]),
        ("--lcd-top", t["lcd_top"]), ("--lcd-bg", t["lcd_bg"]),
        ("--lcd-border", t["lcd_border"]), ("--lcd-line", t["lcd_line"]),
        ("--lcd-ink", t["lcd_ink"]), ("--lcd-dim", t["lcd_dim"]),
        ("--lcd-name", t["lcd_name"]),
        ("--lcd-scroll", mix(t["lcd_line"], t["lcd_ink"], 0.3)),
        ("--lcd-glow", "transparent" if t["key"] == "highcontrast"
                       else rgba(t["lcd_name"], 0.10)),
    ]


def app_block() -> str:
    out = []
    for t in THEMES:
        if t["key"] == "navy":
            continue
        sel = 'html[data-palette="%s"]' % t["key"]
        out.append("  /* %s */\n" % t["name"])
        out.append("  %s {\n%s  }\n" % (
            sel, _decl(app_shared_vars(t) + app_page_vars(t, t["light"], "light"))))
        out.append('  %s[data-theme="dark"] {\n%s  }\n' % (
            sel, _decl(app_page_vars(t, t["dark"], "dark"))))
        if t["key"] == "graygold":
            # The one theme with a gradient: a brushed sheen on the bands.
            out.append("  %s .topbar { background: linear-gradient(180deg, #4a5059 0%%, %s 70%%); }\n"
                       % (sel, t["navy"]))
            out.append("  %s .subbar { background: linear-gradient(180deg, %s 0%%, #40454e 100%%); }\n"
                       % (sel, t["navy2"]))
        if t["key"] == "highcontrast":
            out.append("  %s .lcd, %s .elcard, %s .card { box-shadow: none; }\n"
                       % (sel, sel, sel))
    return "".join(out)


# --- the Numerical Solver page (eqsheet.html) ----------------------------------

def eq_page_vars(t: dict, m: dict, mode: str) -> list:
    return [
        ("--paper", m["bg"]), ("--card", m["card"]),
        ("--card-2", mix(m["card"], m["bg"], 0.5)),
        ("--ink", m["ink"]), ("--ink-2", m["muted"]),
        ("--ink-3", mix(m["muted"], m["bg"], 0.4)),
        ("--line", m["line"]), ("--rule-2", mix(m["line"], m["bg"], 0.5)),
        ("--accent", m["accent"]),
        ("--accent-text", atext(t, m, mode)),
        ("--result-ink", m["hover"] if mode == "light" else m["accent"]),
        ("--badge-bg", mix(m["card"], m["line"], 0.55)),
        ("--lcd", m["field"]), ("--lcd-edge", m["field_line"]),
    ]


def eq_block() -> str:
    out = []
    for t in THEMES:
        if t["key"] == "navy":
            continue
        sel = 'html[data-palette="%s"]' % t["key"]
        shared = [("--navy", t["navy"]), ("--navy-2", t["navy2"]),
                  ("--sky", t["sky"]), ("--banner-sub", t["sub"]),
                  ("--banner-link", t["link"])]
        out.append("  /* %s */\n" % t["name"])
        out.append("  %s {\n%s  }\n" % (sel, _decl(shared + eq_page_vars(t, t["light"], "light"))))
        out.append('  %s[data-theme="dark"] {\n%s  }\n' % (sel, _decl(eq_page_vars(t, t["dark"], "dark"))))
        if t["key"] == "graygold":
            out.append("  %s .topbar { background: linear-gradient(180deg, #4a5059 0%%, %s 70%%); }\n"
                       % (sel, t["navy"]))
            out.append("  %s .subbar { background: linear-gradient(180deg, %s 0%%, #40454e 100%%); }\n"
                       % (sel, t["navy2"]))
    return "".join(out)


BLOCKS = {"templates/index.html": app_block, "templates/eqsheet.html": eq_block}


def splice(text: str, body: str, rel: str) -> str:
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0 or j < i:
        raise SystemExit("palettes.py: the palette markers are missing from %s" % rel)
    return text[:i + len(BEGIN)] + "\n" + body + "  " + text[j:]


def run(write: bool) -> list:
    problems = []
    for rel, make in BLOCKS.items():
        path = SERVER / rel
        raw = path.read_bytes()
        # eqsheet.html is CRLF and index.html LF; each keeps its own.
        crlf = (CR + LF).encode() in raw
        nl = CR + LF if crlf else LF
        text = raw.decode("utf-8").replace(CR + LF, LF)
        want = splice(text, make(), rel)
        if want != text:
            if write:
                path.write_text(want, encoding="utf-8", newline=nl)
                print("palettes.py: wrote the block in %s" % rel)
            else:
                problems.append("%s: the palette block is stale -- run "
                                "`python tools/palettes.py write`" % rel)
    return problems


def main() -> int:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd not in ("write", "check"):
        print(__doc__)
        return 2
    problems = run(write=(cmd == "write"))
    for p in problems:
        print(p)
    if cmd == "check":
        print("palettes check:", "ok" if not problems else "%d problem(s)" % len(problems))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
